"""Ephemeral signed TUF repository helpers for Phase 5.5.2 tests.

Private signing material exists only in test-process memory. No private key is written
to fixtures, Git, artifacts or generated pack targets.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from securesystemslib.signer import CryptoSigner
from tuf.api.metadata import (
    TOP_LEVEL_ROLE_NAMES,
    MetaFile,
    Metadata,
    Root,
    Snapshot,
    TargetFile,
    Targets,
    Timestamp,
)
from tuf.api.serialization.json import JSONSerializer

from tools.pack.tuf_runtime import CURRENT_RUNTIME_VERSION, sha256_prefixed
from tools.search.reference_search import build_projection_bundle
from tools.search.sqlite_search import build_index

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXPIRY = datetime(2030, 1, 1, tzinfo=timezone.utc)
PACK_ID = "atlas:pack:phase552-test"


@dataclass(frozen=True)
class SignedRepoFixture:
    root: Path
    bootstrap_root: bytes
    manifest: dict[str, Any]
    inventory: dict[str, Any]
    spc_bundle: dict[str, Any]


def canonical_json_bytes(value: Any) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        + "\n"
    ).encode("utf-8")


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _metafile(metadata_bytes: bytes, version: int) -> MetaFile:
    return MetaFile(
        version,
        len(metadata_bytes),
        {"sha256": _sha256_hex(metadata_bytes)},
    )


def _write(root: Path, relative: str, data: bytes) -> Path:
    path = root.joinpath(*relative.split("/"))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    return path


def make_signed_repository(
    tmp_path: Path,
    *,
    pack_version: str = "1.0.0-test.1",
    expiry: datetime = DEFAULT_EXPIRY,
    include_search_index: bool = True,
    corrupt_search_index: bool = False,
    invalid_canonical: bool = False,
    inventory_digest_override: str | None = None,
    extra_tuf_target: tuple[str, bytes] | None = None,
) -> SignedRepoFixture:
    repo = Path(tmp_path) / "signed-repo"
    metadata_dir = repo / "metadata"
    targets_dir = repo / "targets"
    metadata_dir.mkdir(parents=True)
    targets_dir.mkdir(parents=True)

    if invalid_canonical:
        canonical_bytes = b'{"schema_version":"1.0.0","record_kind":"claim","id":"not-an-atlas-id"}\n'
    else:
        canonical_record = json.loads(
            (ROOT / "fixtures" / "phase-5.2" / "record-families" / "claim.json").read_text(
                encoding="utf-8"
            )
        )
        canonical_bytes = canonical_json_bytes(canonical_record)

    acceptance = json.loads(
        (ROOT / "fixtures" / "phase-5.4.1" / "acceptance-corpus.json").read_text(
            encoding="utf-8"
        )
    )
    spc_bundle = build_projection_bundle(acceptance)
    spc_bytes = canonical_json_bytes(spc_bundle)

    artifact_bytes: dict[str, tuple[str, bool, bytes]] = {
        "content/canonical-records.jsonl": ("canonical-records", False, canonical_bytes),
        "search/spc.json": ("spc", True, spc_bytes),
    }

    if include_search_index:
        index_path = targets_dir / "search" / "atlas-search.sqlite3"
        index_path.parent.mkdir(parents=True, exist_ok=True)
        if corrupt_search_index:
            index_path.write_bytes(b"not-a-valid-sqlite-index")
        else:
            build_index(spc_bundle, index_path)
        artifact_bytes["search/atlas-search.sqlite3"] = (
            "search-index",
            True,
            index_path.read_bytes(),
        )

    inventory = {
        "inventory_version": "1.0.0",
        "pack_id": PACK_ID,
        "pack_version": pack_version,
        "entries": [
            {
                "source_id": "fixture:phase552",
                "source_name": "Atlas Phase 5.5.2 synthetic fixture",
                "upstream_url": "https://example.invalid/atlas-phase552",
                "source_version_or_commit": "fixture-v1",
                "content_digest": sha256_prefixed(canonical_bytes),
                "redistribution_scope": "included",
                "license_status": "verified-redistributable",
                "license_identifier": "TEST-FIXTURE-ONLY",
                "notice_required": False,
                "attribution": "Synthetic non-production fixture generated by the Phase 5.5.2 test helper.",
                "evidence_url": "https://example.invalid/atlas-phase552/license",
                "reviewed_at": "2026-09-06T10:00:00Z",
            }
        ],
    }
    inventory_bytes = canonical_json_bytes(inventory)

    artifacts = []
    for relative in sorted(artifact_bytes):
        kind, derived, data = artifact_bytes[relative]
        artifacts.append(
            {
                "path": relative,
                "kind": kind,
                "digest": sha256_prefixed(data),
                "length": len(data),
                "derived": derived,
            }
        )

    manifest = {
        "pack_format_version": "1.0.0",
        "pack_id": PACK_ID,
        "pack_version": pack_version,
        "created_at": "2026-09-06T10:00:00Z",
        "canonical_schema_version": "1.0.0",
        "ingestion_contract_version": "1.0.0",
        "search_contract_version": "1.0.0",
        "minimum_runtime_version": CURRENT_RUNTIME_VERSION,
        "canonical_records_digest": sha256_prefixed(canonical_bytes),
        "spc_digest": sha256_prefixed(spc_bytes),
        "source_license_inventory": {
            "path": "atlas/source-license-inventory.json",
            "digest": inventory_digest_override or sha256_prefixed(inventory_bytes),
        },
        "artifacts": artifacts,
    }
    manifest_bytes = canonical_json_bytes(manifest)

    target_data: dict[str, bytes] = {
        "atlas/pack-manifest.json": manifest_bytes,
        "atlas/source-license-inventory.json": inventory_bytes,
    }
    target_data.update({path: value[2] for path, value in artifact_bytes.items()})
    if extra_tuf_target is not None:
        target_data[extra_tuf_target[0]] = extra_tuf_target[1]

    # Write unprefixed logical target layout. The Atlas local TUF fetcher maps
    # consistent-snapshot hash-prefixed requests back to these exact bytes.
    for relative, data in sorted(target_data.items()):
        _write(targets_dir, relative, data)

    md_root = Metadata(Root(expires=expiry))
    md_targets = Metadata(Targets(expires=expiry))
    md_snapshot = Metadata(Snapshot(expires=expiry))
    md_timestamp = Metadata(Timestamp(expires=expiry))
    md_root.signed.consistent_snapshot = True

    signers = {}
    for role in TOP_LEVEL_ROLE_NAMES:
        signer = CryptoSigner.generate_ed25519()
        md_root.signed.add_key(signer.public_key, role)
        signers[role] = signer

    for relative, data in sorted(target_data.items()):
        md_targets.signed.targets[relative] = TargetFile.from_data(relative, data, ["sha256"])

    serializer = JSONSerializer()
    md_targets.sign(signers[Targets.type])
    targets_metadata = md_targets.to_bytes(serializer)

    md_snapshot.signed.meta["targets.json"] = _metafile(
        targets_metadata, md_targets.signed.version
    )
    md_snapshot.sign(signers[Snapshot.type])
    snapshot_metadata = md_snapshot.to_bytes(serializer)

    md_timestamp.signed.snapshot_meta = _metafile(
        snapshot_metadata, md_snapshot.signed.version
    )
    md_timestamp.sign(signers[Timestamp.type])
    timestamp_metadata = md_timestamp.to_bytes(serializer)

    md_root.sign(signers[Root.type])
    root_metadata = md_root.to_bytes(serializer)

    _write(metadata_dir, "root.json", root_metadata)
    _write(metadata_dir, "targets.json", targets_metadata)
    _write(metadata_dir, "snapshot.json", snapshot_metadata)
    _write(metadata_dir, "timestamp.json", timestamp_metadata)

    return SignedRepoFixture(
        root=repo,
        bootstrap_root=root_metadata,
        manifest=manifest,
        inventory=inventory,
        spc_bundle=spc_bundle,
    )


def tamper_json_signature(path: Path) -> None:
    value = json.loads(path.read_text(encoding="utf-8"))
    signature = value["signatures"][0]["sig"]
    replacement = "0" if signature[-1] != "0" else "1"
    value["signatures"][0]["sig"] = signature[:-1] + replacement
    path.write_bytes(canonical_json_bytes(value))
