from __future__ import annotations
from pathlib import Path
import importlib.util, unittest
ROOT=Path(__file__).resolve().parents[2]; SPEC=importlib.util.spec_from_file_location("phase_policy",ROOT/"tools/ingestion/validate_ingestion_authorization.py"); phase_policy=importlib.util.module_from_spec(SPEC); SPEC.loader.exec_module(phase_policy)
class IngestionAuthorizationTests(unittest.TestCase):
    def authorized_paths(self): return sorted(phase_policy.AUTHORIZED_IMPLEMENTATIONS)
    def test_01_current_authorization_allowlist_is_exact(self):
        p532={"ingestion/connectors/mitre-attack-enterprise.json","ingestion/parsers/mitre-attack-stix21.definition.json","ingestion/parsers/mitre_attack_stix.py","ingestion/normalizers/mitre-attack-enterprise.definition.json","ingestion/normalizers/mitre_attack.py"}
        p533={"ingestion/connectors/microsoft-sysmon-docs.json","ingestion/parsers/microsoft-sysmon-markdown.definition.json","ingestion/parsers/microsoft_sysmon_markdown.py","ingestion/parsers/microsoft-sysmon-schema.definition.json","ingestion/parsers/microsoft_sysmon_schema.py","ingestion/normalizers/microsoft-sysmon-docs.definition.json","ingestion/normalizers/microsoft_sysmon_docs.py","ingestion/normalizers/microsoft-sysmon-schema.definition.json","ingestion/normalizers/microsoft_sysmon_schema.py","ingestion/connectors/microsoft-windows-security-event-4688-doc.json","ingestion/parsers/microsoft-windows-security-event-html.definition.json","ingestion/parsers/microsoft_windows_security_event_html.py","ingestion/normalizers/microsoft-windows-security-event-doc.definition.json","ingestion/normalizers/microsoft_windows_security_event_doc.py","ingestion/parsers/microsoft-windows-provider-metadata.definition.json","ingestion/parsers/microsoft_windows_provider_metadata.py","ingestion/normalizers/microsoft-windows-provider-metadata.definition.json","ingestion/normalizers/microsoft_windows_provider_metadata.py"}
        p534={"ingestion/connectors/mitre-d3fend-ontology.json","ingestion/parsers/mitre-d3fend-turtle.definition.json","ingestion/parsers/mitre_d3fend_turtle.py","ingestion/normalizers/mitre-d3fend.definition.json","ingestion/normalizers/mitre_d3fend.py","ingestion/connectors/mitre-car-sample.json","ingestion/parsers/mitre-car-yaml.definition.json","ingestion/parsers/mitre_car_yaml.py","ingestion/normalizers/mitre-car.definition.json","ingestion/normalizers/mitre_car.py","ingestion/parsers/defenseops-export.definition.json","ingestion/parsers/defenseops_export.py","ingestion/normalizers/defenseops-export.definition.json","ingestion/normalizers/defenseops_export.py"}
        self.assertEqual(p532|p533|p534,set(phase_policy.AUTHORIZED_IMPLEMENTATIONS)); self.assertEqual(p534,{p for p,v in phase_policy.AUTHORIZED_IMPLEMENTATIONS.items() if v=="phase-5.3.4"}); self.assertEqual({"phase-5.3.2","phase-5.3.3","phase-5.3.4"},set(phase_policy.AUTHORIZED_IMPLEMENTATIONS.values()))
    def test_02_exact_authorized_set_is_accepted(self): self.assertEqual([],phase_policy.implementation_authorization_errors(self.authorized_paths()))
    def test_03_unknown_connector_fails_closed(self): self.assertTrue(phase_policy.implementation_authorization_errors(self.authorized_paths()+["ingestion/connectors/unapproved.json"]))
    def test_04_unknown_parser_fails_closed(self): self.assertTrue(phase_policy.implementation_authorization_errors(self.authorized_paths()+["ingestion/parsers/unapproved.py"]))
    def test_05_unknown_normalizer_fails_closed(self): self.assertTrue(phase_policy.implementation_authorization_errors(self.authorized_paths()+["ingestion/normalizers/unapproved.py"]))
    def test_06_missing_authorized_asset_fails_closed(self): self.assertTrue(phase_policy.implementation_authorization_errors(self.authorized_paths()[1:]))
    def test_07_noncontrolled_paths_do_not_expand_authority(self): self.assertEqual([],phase_policy.implementation_authorization_errors(self.authorized_paths()+["ingestion/mappings/mitre-d3fend-v1.json","ingestion/source-profiles/mitre-d3fend-ontology.source.json","ingestion/inventories/sysmon-docs-15.21.documentation.json"]))
if __name__=="__main__": unittest.main()
