#!/usr/bin/env python3
from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOW = "2026-10-06T13:01:55Z"
IDS = ["4609","4610","4611","4612","4614","4615","4616","4618","4621","4622"]
STRUCTURAL_SOURCE_ID = "atlas:source:atlas.source:microsoft-windows-security-auditing-provider-26100-4609-4622"
STRUCTURAL_SOURCE_VERSION = "windows-server-2025-build-26100-security-auditing-4609-4622"
RUN_ID = 37467608335
ARTIFACT_ID = 11415372410
ARTIFACT_DIGEST = "sha256:a3909e3fbbe11ed1c22eae1deafa40f070da772045f89b18d3843ecfaa0860b4"
RAW_SHA256 = "sha256-0c27de466bc79e429a97fc2e0649d0d0e0a7d109de975ff79b10a056f80542a4"

def dump(path: Path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

def canonical_json(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)

def digest_without_field(record, field="digest"):
    payload = copy.deepcopy(record)
    payload.pop(field, None)
    return "sha256-" + hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()

def field(key, section, native, typ, meaning, versions, **extra):
    out = {"key":key,"section":section,"native_name":native,"type":typ,"meaning":meaning,"versions":versions}
    out.update(extra)
    return out

COMMON_SUBJECT = [
    field("subject-user-sid","Subject","SubjectUserSid","SID","Security identifier of the subject associated with the event.",["0"]),
    field("subject-user-name","Subject","SubjectUserName","UnicodeString","Account name of the subject associated with the event.",["0"]),
    field("subject-domain-name","Subject","SubjectDomainName","UnicodeString","Domain or computer name associated with the subject account.",["0"]),
    field("subject-logon-id","Subject","SubjectLogonId","HexInt64","Logon-session identifier for correlation with authentication activity.",["0"], correlation="Correlate with logon events such as 4624 when the same Logon ID is available."),
]

SOURCE_URLS = {
    "4609":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/audit-security-state-change",
    "4610":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4610",
    "4611":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4611",
    "4612":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4612",
    "4614":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4614",
    "4615":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4615",
    "4616":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4616",
    "4618":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4618",
    "4621":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4621",
    "4622":"https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4622",
}

TITLES = {
    "4609":"Windows is shutting down",
    "4610":"An authentication package has been loaded by the Local Security Authority",
    "4611":"A trusted logon process has been registered with the Local Security Authority",
    "4612":"Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits",
    "4614":"A notification package has been loaded by the Security Account Manager",
    "4615":"Invalid use of LPC port",
    "4616":"The system time was changed",
    "4618":"A monitored security event pattern has occurred",
    "4621":"Administrator recovered system from CrashOnAuditFail",
    "4622":"A security package has been loaded by the Local Security Authority",
}
SUBCATEGORY = {
    "4609":"Audit Security State Change","4610":"Audit Security System Extension","4611":"Audit Security System Extension",
    "4612":"Audit System Integrity","4614":"Audit Security System Extension","4615":"Audit System Integrity",
    "4616":"Audit Security State Change","4618":"Audit System Integrity","4621":"Audit Security State Change","4622":"Audit Security System Extension",
}

PROVIDER_VERSIONS = {
    "4609":[{"version":0,"level":"win:Informational","fields":[]}],
    "4610":[{"version":0,"level":"win:Informational","fields":[("AuthenticationPackageName","win:UnicodeString","xs:string")]}],
    "4611":[{"version":0,"level":"win:Informational","fields":[("SubjectUserSid","win:SID","xs:string"),("SubjectUserName","win:UnicodeString","xs:string"),("SubjectDomainName","win:UnicodeString","xs:string"),("SubjectLogonId","win:HexInt64","win:HexInt64"),("LogonProcessName","win:UnicodeString","xs:string")]}],
    "4612":[{"version":0,"level":"win:Informational","fields":[("AuditsDiscarded","win:UInt32","xs:unsignedInt")]}],
    "4614":[{"version":0,"level":"win:Informational","fields":[("NotificationPackageName","win:UnicodeString","xs:string")]}],
    "4615":[{"version":0,"level":"win:Informational","fields":[("SubjectUserSid","win:SID","xs:string"),("SubjectUserName","win:UnicodeString","xs:string"),("SubjectDomainName","win:UnicodeString","xs:string"),("SubjectLogonId","win:HexInt64","win:HexInt64"),("InvalidCallName","win:UnicodeString","xs:string"),("ServerPortName","win:UnicodeString","xs:string"),("ProcessId","win:Pointer","win:HexInt64"),("ProcessName","win:UnicodeString","xs:string")]}],
    "4616":[
        {"version":0,"level":"win:Informational","fields":[("SubjectUserSid","win:SID","xs:string"),("SubjectUserName","win:UnicodeString","xs:string"),("SubjectDomainName","win:UnicodeString","xs:string"),("SubjectLogonId","win:HexInt64","win:HexInt64"),("PreviousDate","win:UnicodeString","xs:string"),("PreviousTime","win:UnicodeString","xs:string"),("NewDate","win:UnicodeString","xs:string"),("NewTime","win:UnicodeString","xs:string"),("ProcessId","win:Pointer","win:HexInt64"),("ProcessName","win:UnicodeString","xs:string")]},
        {"version":1,"level":"win:Informational","fields":[("SubjectUserSid","win:SID","xs:string"),("SubjectUserName","win:UnicodeString","xs:string"),("SubjectDomainName","win:UnicodeString","xs:string"),("SubjectLogonId","win:HexInt64","win:HexInt64"),("PreviousTime","win:FILETIME","xs:dateTime"),("NewTime","win:FILETIME","xs:dateTime"),("ProcessId","win:Pointer","win:HexInt64"),("ProcessName","win:UnicodeString","xs:string")]},
    ],
    "4618":[{"version":0,"level":"win:Informational","fields":[("EventId","win:UInt32","xs:unsignedInt"),("ComputerName","win:UnicodeString","xs:string"),("TargetUserSid","win:SID","xs:string"),("TargetUserName","win:UnicodeString","xs:string"),("TargetUserDomain","win:UnicodeString","xs:string"),("TargetLogonId","win:HexInt64","win:HexInt64"),("EventCount","win:UInt32","xs:unsignedInt"),("Duration","win:UnicodeString","xs:string")]}],
    "4621":[{"version":0,"level":"win:Informational","fields":[("CrashOnAuditFailValue","win:UnicodeString","xs:string")]}],
    "4622":[{"version":0,"level":"win:Informational","fields":[("SecurityPackageName","win:UnicodeString","xs:string")]}],
}

def structural_inventory():
    identities=[]
    for eid in IDS:
        versions=[]
        for ver in PROVIDER_VERSIONS[eid]:
            versions.append({"version":ver["version"],"field_count":len(ver["fields"]),"level":ver["level"],"fields":[{"name":n,"in_type":i,"out_type":o} for n,i,o in ver["fields"]]})
        identities.append({"event_id":eid,"versions":versions})
    doc={
        "ingestion_contract_version":"1.0.0","inventory_contract_version":"1.0.0",
        "inventory_id":"atlas:inventory:atlas.ingestion:windows-security-auditing-4609-4622-26100","inventory_kind":"telemetry",
        "declared_scope":"Microsoft-Windows-Security-Auditing provider Event IDs 4609, 4610, 4611, 4612, 4614, 4615, 4616, 4618, 4621 and 4622 linked to the Security channel on a controlled Windows Server 2025 Datacenter build 26100 GitHub runner",
        "source_ids":[STRUCTURAL_SOURCE_ID],"inventory_method":"provider-runtime-metadata","inventory_source_version":STRUCTURAL_SOURCE_VERSION,
        "expected_identity_count":10,"identity_dimensions":["provider","channel","native-id","product","platform","version"],
        "scope_metadata":{"provider":"Microsoft-Windows-Security-Auditing","channel":"Security","product":"Windows Server 2025 Datacenter","platform":"Windows","windows_build":"26100","architecture":"64-bit","workflow_run_id":RUN_ID,"artifact_id":ARTIFACT_ID,"artifact_digest":ARTIFACT_DIGEST,"raw_artifact_sha256":RAW_SHA256,"provider_event_version_definition_count":11,"provider_unique_event_id_count":10,"expected_identities":identities,"completeness_semantics":"bounded structural evidence for ten Security-Auditing identities already contained within the separately frozen 423-ID provider denominator; this inventory does not create or alter that denominator"},
        "guardrails":{"max_unexplained_shrink_percent":0,"max_unexplained_growth_percent":0},
    }
    doc["digest"]=digest_without_field(doc)
    return doc

def source_record(source_id, canonical_key, title, urls, *, source_class="tier-a-authoritative", official="official", redistribution="restricted", notes=None, cadence="documentation-maintained", stale=180, change=None):
    return {"schema_version":"1.0.0","record_kind":"source","id":source_id,"record_revision":1,"created_at":NOW,"updated_at":NOW,"curation_status":"validated","namespace":"atlas.source","canonical_key":canonical_key,"title":title,"publisher":"Microsoft" if "microsoft-" in canonical_key else "Monterey Technology Group, Inc.","source_class":source_class,"canonical_urls":urls,"official_status":official,"license":{"status":"unknown" if official=="official" else "restricted"},"redistribution":{"policy":redistribution,"notes":notes or ("ATLAS stores independently authored normalized facts and source locators; substantial Microsoft documentation prose is not redistributed." if official=="official" else "External analyst-reference and coverage benchmark only. ATLAS does not package substantial page prose/examples without explicit permission from the rights holder.")},"freshness_policy":{"expected_update_cadence":cadence,"stale_after_days":stale},"change_detection_policy":change or {"strategy":"content-diff","notes":"Material identity, version, payload, or semantic changes require controlled re-review."}}

def write_sources():
    srcdir=ROOT/"content/encyclopedia/sources"
    provider=source_record(STRUCTURAL_SOURCE_ID,"microsoft-windows-security-auditing-provider-26100-4609-4622","Microsoft-Windows-Security-Auditing Security Provider Metadata — Windows Server 2025 build 26100 — Event IDs 4609–4622 bounded batch",["https://learn.microsoft.com/en-us/windows/win32/wes/windows-event-log"],cadence="provider-build-bound",change={"strategy":"checksum","notes":f"Bound to GitHub workflow run {RUN_ID}, artifact {ARTIFACT_ID}, artifact digest {ARTIFACT_DIGEST}, raw discovery JSON {RAW_SHA256}, and normalized inventory ingestion/inventories/windows-security-auditing-4609-4622-26100.telemetry.json."})
    dump(srcdir/"microsoft-windows-security-auditing-provider-26100-4609-4622.json",provider)
    for eid in IDS:
        ms=source_record(f"atlas:source:atlas.source:microsoft-windows-security-event-{eid}",f"microsoft-windows-security-event-{eid}",f"Microsoft Windows Security Auditing Event {eid} Documentation",[SOURCE_URLS[eid]],change={"strategy":"content-diff","notes":f"Event {eid} documentation is semantic authority where available; controlled Windows Server 2025 provider evidence remains structural authority for current provider/version field shape."})
        dump(srcdir/f"microsoft-windows-security-event-{eid}.json",ms)
        uws=source_record(f"atlas:source:atlas.source:ultimate-windows-security-event-{eid}",f"ultimate-windows-security-event-{eid}",f"Ultimate Windows Security — Windows Security Log Event ID {eid}",[f"https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid={eid}"],source_class="tier-c-secondary-research",official="secondary-reference",redistribution="prohibited",cadence="web-reference",stale=90,change={"strategy":"manual","notes":"No automated or bulk ingestion is authorized. Review remains controlled under the ATLAS source-authority policy."})
        dump(srcdir/f"ultimate-windows-security-event-{eid}.json",uws)

def event_versions(eid):
    rows=[]
    for v in PROVIDER_VERSIONS[eid]:
        notes="Controlled Windows Server 2025 provider structural shape."
        if eid=="4616" and v["version"]==0: notes="Controlled provider v0 exposes separate PreviousDate/PreviousTime and NewDate/NewTime fields plus process context; this current provider shape is preserved explicitly rather than flattened into the v1 documentation shape."
        elif eid=="4616" and v["version"]==1: notes="Microsoft documentation and controlled provider evidence align on FILETIME PreviousTime/NewTime plus process context."
        rows.append({"version":str(v["version"]),"generation":"Documented and/or provider-validated shape","field_count":len(v["fields"]),"notes":notes})
    return rows

def common_event(eid, summary, fields, analysis, correlations, requirements, interpretation, aliases=None, extra_overview=None):
    ov={"summary":summary,"category":"System","subcategory":SUBCATEGORY[eid],"event_type":"Success","provider_level":"Informational","event_versions":event_versions(eid)}
    if extra_overview: ov.update(extra_overview)
    srcver="event-4616-v1-doc" if eid=="4616" else ("audit-security-state-change-doc" if eid=="4609" else f"event-{eid}-v0-doc")
    return {"id":f"atlas:event:microsoft.windows.security:{eid}","namespace":"microsoft.windows.security","canonical_key":eid,"title":f"Windows Security Event {eid} — {TITLES[eid]}","provider":"Microsoft-Windows-Security-Auditing","channel":"Security","product":"Windows Security Auditing","platform":"Windows","native_event_id":eid,"aliases":[eid,f"Event ID {eid}",f"Windows {eid}",*(aliases or [TITLES[eid]])],"lifecycle":"current","source_id":f"atlas:source:atlas.source:microsoft-windows-security-event-{eid}","source_version":srcver,"source_url":SOURCE_URLS[eid],"source_locator":f"{eid}(S): {TITLES[eid]}","structural_source":{"source_id":STRUCTURAL_SOURCE_ID,"source_version":STRUCTURAL_SOURCE_VERSION,"locator":f"Microsoft-Windows-Security-Auditing / Security / Event ID {eid} / versions "+",".join(str(v["version"]) for v in PROVIDER_VERSIONS[eid])},"external_reference":{"source_id":f"atlas:source:atlas.source:ultimate-windows-security-event-{eid}","url":f"https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid={eid}","role":"PRIMARY_EXTERNAL_QUICK_DETAIL_REFERENCE","redistribution":"source-link-and-coverage-benchmark-only"},"overview":ov,"collection":{"requirements":requirements,"interpretation_note":interpretation},"correlations":correlations,"analysis":analysis,"fields":fields}

def events():
    out=[]
    out.append(common_event("4609","Represents the defined Windows Security-Auditing shutdown event. Microsoft documents the identity but notes that current Windows does not invoke it, while the Server 2025 provider still exposes a Version 0 zero-field structural definition.",[],["Treat Event 4609 as a defined shutdown identity, not as a guaranteed shutdown marker: Microsoft states that the operating system does not currently invoke it.","Do not infer an unclean shutdown merely because 4609 is absent; correlate 4608 and independent System/uptime telemetry instead.","Do not invent EventData fields for the controlled Version 0 provider shape; field count is zero."],[{"target":"4608","key":"Computer + time","purpose":"compare a defined audited shutdown boundary with the next audited startup","limitation":"Absence of 4609 is expected on current Windows and is not proof of an abnormal shutdown."}],["Preserve the Security provider/system envelope if Event 4609 is ever observed.","Use independent shutdown/startup telemetry for operational conclusions because Microsoft documents this event as defined but not currently generated."],"The identity is valid and provider-defined, but present-day absence is expected. Detection logic must not require this event as proof that Windows shut down cleanly.",aliases=["Windows shutdown","Windows is shutting down"],extra_overview={"generation_note":"Microsoft documents Event 4609 as defined but not currently invoked by the operating system."}))
    out.append(common_event("4610","Records loading of an authentication package by the Local Security Authority, exposing the loaded authentication-package identity.",[field("authentication-package-name","Security Extension","AuthenticationPackageName","UnicodeString","Name of the authentication package loaded by LSA.",["0"])],["Baseline expected authentication packages and investigate newly introduced or unexpected package DLL/name combinations.","Correlate unexpected package loading with startup context, software installation, registry changes, code-signing evidence and process/module telemetry.","Treat package loading as security-extension telemetry; it can be legitimate and is not a malicious verdict by itself."],[{"target":"4622","key":"Computer + time + package identity","purpose":"compare authentication-package and security-package loading activity around LSA initialization"}],["Audit Security System Extension success auditing should be enabled where package-load visibility is required.","Collectors must preserve AuthenticationPackageName."],"Common packages can load during normal startup. Prioritize deviations from an approved baseline and unexpected dynamic additions."))
    out.append(common_event("4611","Records confirmation/registration of a trusted logon process with LSA and preserves the subject plus logon-process name.",[*COMMON_SUBJECT,field("logon-process-name","Logon Process","LogonProcessName","UnicodeString","Name of the trusted logon process registered/confirmed with LSA.",["0"])],["Review trusted logon-process names against an approved baseline and prioritize registrations under unexpected subject identities.","Use SubjectLogonId to pivot to authentication context and correlate the process name with endpoint process/module telemetry.","Microsoft notes this event commonly appears during startup or authentication activity, so baseline context is essential."],[{"target":"4624","key":"SubjectLogonId + Computer + time","purpose":"correlate trusted logon-process registration with nearby successful logon sessions"}],["Audit Security System Extension success auditing should be enabled.","Collectors must preserve the four Subject fields and LogonProcessName."],"SYSTEM-context registrations and known Windows logon processes are commonly legitimate; unexpected subject or process values warrant investigation."))
    out.append(common_event("4612","Signals exhaustion of internal resources used to queue audit messages, with a count of discarded audits and therefore a potential Security-log completeness gap.",[field("audits-discarded","Audit Queue","AuditsDiscarded","UInt32","Number of audit messages discarded when audit queuing resources were exhausted.",["0"])],["Treat every 4612 as an audit-integrity issue because it explicitly indicates lost audit records.","Investigate event-generation rate, disk/event-log throughput, memory/resource pressure and event-log service connectivity around the occurrence.","Quantify the potential visibility gap using AuditsDiscarded and surrounding collector/service telemetry."],[{"target":"1101","key":"Computer + time","purpose":"compare audit-queue loss with EventLog transport-drop evidence when both are present"},{"target":"1108","key":"Computer + time","purpose":"check for nearby Event Log processing failures"}],["Audit System Integrity success auditing and Security-log collection must preserve Event 4612.","Collectors must preserve AuditsDiscarded and surrounding timestamps."],"This is a logging-integrity signal and may result from resource or throughput problems; investigate root cause without assuming attacker activity."))
    out.append(common_event("4614","Records loading of a notification package by the Security Account Manager; on modern Windows this is closely associated with password-filter notification packages.",[field("notification-package-name","Security Extension","NotificationPackageName","UnicodeString","Name of the notification package loaded by SAM.",["0"])],["Maintain an approved notification/password-filter package baseline and investigate unexpected additions or path/name changes.","Correlate package changes with LSA Notification Packages registry changes, software installation and code-signing/module evidence.","Treat known enterprise password-filter products as expected only when approved and integrity-validated."],[{"target":"4610","key":"Computer + time","purpose":"review adjacent LSA security-extension loading during startup or configuration change"},{"target":"4622","key":"Computer + time","purpose":"review adjacent security-package loading"}],["Audit Security System Extension success auditing should be enabled.","Collectors must preserve NotificationPackageName."],"Notification packages can be legitimate password filters. Unexpected package identities or unapproved changes are the primary investigation signal."))
    out.append(common_event("4615","Represents invalid use of the LPC port reserved for Local Security Authority communication and exposes subject, invalid call, server-port and process context.",[*COMMON_SUBJECT,field("invalid-call-name","LPC Context","InvalidCallName","UnicodeString","Name or classification of the invalid LPC call recorded by the provider.",["0"]),field("server-port-name","LPC Context","ServerPortName","UnicodeString","LPC server port name involved in the invalid-use condition.",["0"]),field("process-id","Process Information","ProcessId","Pointer/HexInt64","Process identifier associated with the invalid LPC-port use.",["0"],correlation="Correlate with process creation telemetry using PID plus time because PIDs are reusable."),field("process-name","Process Information","ProcessName","UnicodeString/path","Process image name/path associated with the invalid LPC-port use.",["0"])],["If observed, investigate the reported process, image integrity, signer, parent/command line and access to the LSA communication channel.","Use ProcessId with event time and independent process-creation telemetry because PID reuse can otherwise misattribute activity.","Microsoft documentation states that this event appears not to occur normally, so any real observation deserves validation and triage."],[{"target":"4688","key":"ProcessId + Computer + time","purpose":"resolve process creation context for the process named in Event 4615","limitation":"PID reuse requires tight time correlation."}],["Audit System Integrity success auditing should be enabled where this identity is relevant.","Collectors should preserve all subject, LPC and process fields if the event occurs."],"Microsoft notes that this event appears never to occur. If observed, first validate authenticity/collection integrity, then investigate the process and LPC interaction.",extra_overview={"generation_note":"Microsoft documentation states that this event appears never to occur."}))
    fields4616=[field("subject-user-sid","Subject","SubjectUserSid","SID","Security identifier of the account associated with the system-time change.",["0","1"]),field("subject-user-name","Subject","SubjectUserName","UnicodeString","Account name associated with the system-time change.",["0","1"]),field("subject-domain-name","Subject","SubjectDomainName","UnicodeString","Domain or computer name associated with the subject account.",["0","1"]),field("subject-logon-id","Subject","SubjectLogonId","HexInt64","Logon-session identifier for the account associated with the time change.",["0","1"],correlation="Correlate with logon telemetry such as 4624."),field("previous-date","Time Change","PreviousDate","UnicodeString","Provider-native Version 0 previous-date component; Version 1 no longer exposes this separate field.",["0"]),field("previous-time","Time Change","PreviousTime","Version-dependent: UnicodeString (v0) / FILETIME (v1)","Previous system time. The controlled provider encodes it as UnicodeString in v0 and FILETIME/xs:dateTime in v1.",["0","1"],notes="Do not flatten v0 and v1 types."),field("new-date","Time Change","NewDate","UnicodeString","Provider-native Version 0 new-date component; Version 1 no longer exposes this separate field.",["0"]),field("new-time","Time Change","NewTime","Version-dependent: UnicodeString (v0) / FILETIME (v1)","New system time. The controlled provider encodes it as UnicodeString in v0 and FILETIME/xs:dateTime in v1.",["0","1"],notes="Do not flatten v0 and v1 types."),field("process-id","Process Information","ProcessId","Pointer/HexInt64","Process identifier associated with the system-time change in the controlled provider shapes.",["0","1"],correlation="Correlate with process creation telemetry using PID plus event time."),field("process-name","Process Information","ProcessName","UnicodeString/path","Process image name/path associated with the system-time change in the controlled provider shapes.",["0","1"])]
    out.append(common_event("4616","Records a system-time change. Controlled Server 2025 provider evidence preserves distinct Version 0 and Version 1 payloads rather than flattening them.",fields4616,["Prioritize time changes performed by identities or processes outside the expected Windows Time service baseline.","Correlate PreviousTime/NewTime with surrounding authentication, process, service and log timestamps because clock changes can affect timeline analysis.","Preserve the Event.Version: v0 and v1 have materially different field sets and time encodings.","Do not assume every time correction is suspicious; normal synchronization commonly occurs under service context."],[{"target":"4624","key":"SubjectLogonId + Computer + time","purpose":"resolve the subject logon context for an interactive/admin-driven time change"},{"target":"4688","key":"ProcessId + Computer + time","purpose":"resolve process creation context for the process associated with the time change","limitation":"PID reuse requires time-bounded correlation."}],["Audit Security State Change success auditing should be enabled.","Collectors must preserve Event.Version and all native fields so v0/v1 shapes can be interpreted correctly."],"Normal Windows Time corrections are common. Unexpected subject identity, process image, magnitude/frequency, or timing relative to suspicious activity increases security relevance.",extra_overview={"version_reconciliation_note":"Microsoft's published Event 4616 page illustrates Version 1; controlled Windows Server 2025 provider metadata also exposes Version 0 with 10 fields and Version 1 with 8 fields. ATLAS preserves both shapes explicitly."}))
    out.append(common_event("4618","Records an intentionally generated monitored-security-event pattern carrying an organization-defined event identifier, computer/user context, count and duration.",[field("event-id","Pattern Context","EventId","UInt32","Payload-defined monitored pattern identifier supplied to the audit-generation API; it is not the outer Windows Event ID 4618.",["0"],notes="This inner EventId is payload context and must not be confused with the record identity 4618."),field("computer-name","Pattern Context","ComputerName","UnicodeString","Computer name supplied as monitored-pattern context.",["0"]),field("target-user-sid","Target Account","TargetUserSid","SID","Target/user SID supplied with the monitored pattern when present.",["0"]),field("target-user-name","Target Account","TargetUserName","UnicodeString","Target/user name supplied with the monitored pattern when present.",["0"]),field("target-user-domain","Target Account","TargetUserDomain","UnicodeString","Target/user domain supplied with the monitored pattern when present.",["0"]),field("target-logon-id","Target Account","TargetLogonId","HexInt64","Target/user logon identifier supplied with the monitored pattern when present.",["0"]),field("event-count","Pattern Context","EventCount","UInt32","Count supplied for the monitored security event pattern.",["0"]),field("duration","Pattern Context","Duration","UnicodeString","Duration/context string supplied for the monitored pattern.",["0"])],["Interpret 4618 according to the organization/application that intentionally generated it; Microsoft documents external invocation rather than an autonomous Windows detection verdict.","Preserve the inner EventId separately from the outer Windows Event ID 4618 to prevent identity confusion.","Validate the generator's SeAuditPrivilege use and application context when unexpected 4618 events appear."],[{"target":"Payload EventId","key":"EventId","purpose":"resolve the organization-defined monitored event/pattern referenced inside the 4618 payload","limitation":"The payload EventId is not the outer Windows Event ID."}],["Audit System Integrity success auditing and collection must preserve Event 4618 where custom monitored-pattern events are used.","Collectors must preserve all eight payload fields and must not map the inner EventId over the outer Event ID."],"Microsoft documents Event 4618 as intentionally/external generated. Its security meaning depends on the producer and supplied pattern data rather than the event number alone.",extra_overview={"generation_note":"Microsoft documents invocation through AuthziGenerateAdminAlertAudit with SeAuditPrivilege."}))
    out.append(common_event("4621","Records administrator recovery after a CrashOnAuditFail-triggered system halt/reboot and exposes the CrashOnAuditFail value.",[field("crash-on-audit-fail-value","Recovery Context","CrashOnAuditFailValue","UnicodeString","CrashOnAuditFail configuration/state value recorded during recovery.",["0"])],["Treat any 4621 as high-priority audit-integrity evidence because Microsoft states auditable activity might have been lost before recovery.","Investigate why Security auditing could not be sustained, whether CrashOnAuditFail policy was expected, and the period of possible telemetry loss.","Correlate with reboot/startup, Security log capacity, Event Log service and audit-loss events."],[{"target":"4608","key":"Computer + time","purpose":"correlate recovery with the subsequent audited startup boundary"},{"target":"4612","key":"Computer + time","purpose":"check for audit-queue exhaustion preceding the CrashOnAuditFail condition"},{"target":"1104","key":"Computer + time","purpose":"check whether Security-log capacity problems contributed to the condition"}],["Audit Security State Change success auditing and Security-log forwarding should preserve Event 4621.","Collectors must preserve CrashOnAuditFailValue and nearby reboot/audit-integrity telemetry."],"Microsoft recommends alerting on any occurrence. The event indicates recovery from a state in which audit recording failed sufficiently to trigger CrashOnAuditFail behavior."))
    out.append(common_event("4622","Records loading of a security package by the Local Security Authority and exposes the package identity.",[field("security-package-name","Security Extension","SecurityPackageName","UnicodeString","Name/path and security-package identity loaded by LSA.",["0"])],["Baseline expected LSA security packages and investigate new, unsigned, unusual-path or otherwise unapproved package identities.","Correlate unexpected package loading with LSA registry/configuration changes, process/module telemetry and software installation.","Dynamic package loading is possible, so an occurrence outside startup context can be especially relevant when unapproved."],[{"target":"4610","key":"Computer + time + package identity","purpose":"compare security-package and authentication-package loading around LSA initialization"},{"target":"4614","key":"Computer + time","purpose":"review adjacent notification/password-filter package loading"}],["Audit Security System Extension success auditing should be enabled.","Collectors must preserve SecurityPackageName."],"Known Windows security packages load legitimately. Focus on deviation from an approved package baseline, integrity/signature anomalies and unexpected dynamic loading."))
    return out

def update_blueprint():
    path=ROOT/"content/encyclopedia/approved-exemplars.json"; doc=json.loads(path.read_text(encoding="utf-8"))
    existing={str(e.get("native_event_id")) for e in doc["events"] if e.get("namespace")=="microsoft.windows.security"}; dup=existing.intersection(IDS)
    if dup: raise SystemExit(f"Refusing duplicate Windows Security exemplars: {sorted(dup)}")
    insert_at=next(i for i,e in enumerate(doc["events"]) if e.get("id")=="atlas:event:microsoft.windows.security:4624")
    doc["events"][insert_at:insert_at]=events(); dump(path,doc)

def update_coverage():
    path=ROOT/"content/encyclopedia/coverage-manifest.json"; doc=json.loads(path.read_text(encoding="utf-8")); bench=doc["windows_security_log_review_benchmark"]
    covered=sorted(set(bench["covered_event_ids"])|set(IDS),key=int); bench["covered_event_ids"]=covered; bench["encyclopedia_grade_listed_id_count"]=len(covered); bench["remaining_listed_id_count"]=bench["listed_unique_event_id_count"]-len(covered); bench["completion_ratio"]=f"{len(covered)}/{bench['listed_unique_event_id_count']}"; bench["completion_percent"]=round(len(covered)/bench["listed_unique_event_id_count"]*100,2)
    fam=next(x for x in doc["families"] if x["id"]=="windows-security-auditing"); fam["denominator_count"]=423; fam["encyclopedia_grade_count"]=20; fam["remaining_count"]=403; dump(path,doc)

def rebuild_provider_snapshot():
    module_path=ROOT/"tools/content/build_windows_security_coverage_snapshot.py"; spec=importlib.util.spec_from_file_location("coverage_builder",module_path); module=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(module); snapshot=module.build_snapshot()
    if (snapshot["denominator_count"],snapshot["encyclopedia_grade_count"],snapshot["remaining_count"])!=(423,20,403): raise SystemExit(f"Unexpected rebuilt Security-Auditing coverage: {snapshot['completion_ratio']}")
    (ROOT/"content/encyclopedia/windows-security-auditing-26100.33296-coverage.snapshot.json").write_text(json.dumps(snapshot,ensure_ascii=False,sort_keys=True,indent=2)+"\n",encoding="utf-8")

def update_existing_tests():
    p=ROOT/"tests/phase51010/test_windows_security_coverage_snapshot.py"; text=p.read_text(encoding="utf-8"); text=text.replace('assert snapshot["encyclopedia_grade_count"] == 10','assert snapshot["encyclopedia_grade_count"] == 20').replace('assert snapshot["remaining_count"] == 413','assert snapshot["remaining_count"] == 403').replace('assert snapshot["completion_ratio"] == "10/423"','assert snapshot["completion_ratio"] == "20/423"').replace('assert snapshot["completion_percent"] == 2.36','assert snapshot["completion_percent"] == 4.73'); p.write_text(text,encoding="utf-8")
    p=ROOT/"tests/phase51010/test_windows_security_eventlog_1100_series.py"; text=p.read_text(encoding="utf-8"); old='assert (b["listed_unique_event_id_count"],b["encyclopedia_grade_listed_id_count"],b["remaining_listed_id_count"],b["completion_ratio"],b["completion_percent"])==(422,16,406,"16/422",3.79); assert b["covered_event_ids"][:6]==IDS; w=next(item for item in m["families"] if item["id"]=="windows-security-auditing"); assert (w["denominator_count"],w["encyclopedia_grade_count"],w["remaining_count"])==(423,10,413)'; new='assert b["listed_unique_event_id_count"]==422; assert set(IDS).issubset(set(b["covered_event_ids"])); assert b["encyclopedia_grade_listed_id_count"]>=16; assert b["remaining_listed_id_count"]==422-b["encyclopedia_grade_listed_id_count"]; w=next(item for item in m["families"] if item["id"]=="windows-security-auditing"); assert w["denominator_count"]==423; assert w["encyclopedia_grade_count"]>=10; assert w["remaining_count"]==423-w["encyclopedia_grade_count"]'
    if old not in text: raise SystemExit("Expected first-batch coverage assertion not found")
    p.write_text(text.replace(old,new),encoding="utf-8")

def write_batch_tests():
    p=ROOT/"tests/phase51010/test_windows_security_auditing_4609_4622.py"
    p.write_text(r'''#!/usr/bin/env python3
from __future__ import annotations
import importlib.util, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
IDS=["4609","4610","4611","4612","4614","4615","4616","4618","4621","4622"]
STRUCTURAL="atlas:source:atlas.source:microsoft-windows-security-auditing-provider-26100-4609-4622"
def load_module(name,path):
    spec=importlib.util.spec_from_file_location(name,path); module=importlib.util.module_from_spec(spec); spec.loader.exec_module(module); return module
builder=load_module("securitybatch_builder",ROOT/"tools/content/build_encyclopedia_records.py"); validator=load_module("securitybatch_validator",ROOT/"tools/validate_phase52.py")
def records(): return builder.build_records()
def by_id(): return {item["id"]:item for item in records()}
def blueprints():
    doc=json.loads((ROOT/"content/encyclopedia/approved-exemplars.json").read_text(encoding="utf-8")); return {str(item["native_event_id"]):item for item in doc["events"] if item.get("namespace")=="microsoft.windows.security"}
def test_01_batch_records_validate_canonical_v1():
    pairs=[(ROOT/"content/encyclopedia/approved-exemplars.json",item) for item in records()]; errors=validator.validate_schema_records(pairs)+validator.validate_semantics(pairs,validator.load_registries()); assert errors==[],"\n".join(errors)
def test_02_all_ids_are_security_auditing_and_searchable():
    pairs=[(ROOT/"content/encyclopedia/approved-exemplars.json",item) for item in records()]; data=by_id()
    for eid in IDS:
        rid=f"atlas:event:microsoft.windows.security:{eid}"; assert rid in data; ctx=data[rid]["native_identifiers"][0]["context"]; assert (ctx["provider"],ctx["channel"])==("Microsoft-Windows-Security-Auditing","Security"); assert validator.resolve_query(pairs,eid)==[rid]
def test_03_provider_structural_shapes_are_exact():
    bp=blueprints(); expected={"4609":{"0":0},"4610":{"0":1},"4611":{"0":5},"4612":{"0":1},"4614":{"0":1},"4615":{"0":8},"4616":{"0":10,"1":8},"4618":{"0":8},"4621":{"0":1},"4622":{"0":1}}
    for eid,want in expected.items(): assert {row["version"]:row["field_count"] for row in bp[eid]["overview"]["event_versions"]}==want
    assert bp["4609"]["fields"]==[]; v4616={f["native_name"]:f for f in bp["4616"]["fields"]}; assert v4616["PreviousDate"]["versions"]==["0"] and v4616["NewDate"]["versions"]==["0"]; assert v4616["PreviousTime"]["versions"]==["0","1"] and "FILETIME" in v4616["PreviousTime"]["type"]; assert bp["4618"]["fields"][0]["native_name"]=="EventId" and "not the outer Windows Event ID 4618" in bp["4618"]["fields"][0]["meaning"]
def test_04_structural_evidence_is_attached():
    data=by_id()
    for eid in IDS:
        subject=f"atlas:event:microsoft.windows.security:{eid}"; claims=[x for x in data.values() if x.get("record_kind")=="claim" and x.get("subject_id")==subject and x.get("predicate")=="telemetry.represents"]; assert len(claims)==1; assert STRUCTURAL in {ev["source_id"] for ev in claims[0]["evidence"]}
def test_05_uws_remains_reference_only():
    data=by_id()
    for eid in IDS: assert data[f"atlas:source:atlas.source:ultimate-windows-security-event-{eid}"]["redistribution"]["policy"]=="prohibited"
def test_06_coverage_moves_both_benchmark_and_provider_numerator():
    m=json.loads((ROOT/"content/encyclopedia/coverage-manifest.json").read_text(encoding="utf-8")); b=m["windows_security_log_review_benchmark"]; assert (b["listed_unique_event_id_count"],b["encyclopedia_grade_listed_id_count"],b["remaining_listed_id_count"],b["completion_ratio"],b["completion_percent"])==(422,26,396,"26/422",6.16); assert set(IDS).issubset(set(b["covered_event_ids"])); w=next(x for x in m["families"] if x["id"]=="windows-security-auditing"); assert (w["denominator_count"],w["encyclopedia_grade_count"],w["remaining_count"])==(423,20,403); s=json.loads((ROOT/"content/encyclopedia/windows-security-auditing-26100.33296-coverage.snapshot.json").read_text(encoding="utf-8")); assert (s["denominator_count"],s["encyclopedia_grade_count"],s["remaining_count"],s["completion_ratio"],s["completion_percent"])==(423,20,403,"20/423",4.73); byevent={x["event_id"]:x for x in s["events"]}; [(_ for _ in ()).throw(AssertionError(eid)) for eid in IDS if byevent[eid]["coverage_state"]!="ENCYCLOPEDIA_GRADE"]
def test_07_discovery_evidence_is_checksum_bound():
    inv=json.loads((ROOT/"ingestion/inventories/windows-security-auditing-4609-4622-26100.telemetry.json").read_text(encoding="utf-8")); s=inv["scope_metadata"]; assert inv["expected_identity_count"]==10; assert (s["provider"],s["channel"],s["windows_build"])==("Microsoft-Windows-Security-Auditing","Security","26100"); assert (s["workflow_run_id"],s["artifact_id"])==(37467608335,11415372410); assert s["artifact_digest"]=="sha256:a3909e3fbbe11ed1c22eae1deafa40f070da772045f89b18d3843ecfaa0860b4"; assert s["raw_artifact_sha256"]=="sha256-0c27de466bc79e429a97fc2e0649d0d0e0a7d109de975ff79b10a056f80542a4"; assert s["provider_event_version_definition_count"]==11; assert [x["event_id"] for x in s["expected_identities"]]==IDS
def test_08_4616_versions_are_not_flattened():
    inv=json.loads((ROOT/"ingestion/inventories/windows-security-auditing-4609-4622-26100.telemetry.json").read_text(encoding="utf-8")); row=next(x for x in inv["scope_metadata"]["expected_identities"] if x["event_id"]=="4616"); assert [v["version"] for v in row["versions"]]==[0,1] and [v["field_count"] for v in row["versions"]]==[10,8]; v0={f["name"]:(f["in_type"],f["out_type"]) for f in row["versions"][0]["fields"]}; v1={f["name"]:(f["in_type"],f["out_type"]) for f in row["versions"][1]["fields"]}; assert v0["PreviousTime"]==("win:UnicodeString","xs:string") and v1["PreviousTime"]==("win:FILETIME","xs:dateTime") and "PreviousDate" in v0 and "PreviousDate" not in v1
''',encoding="utf-8")

def update_docs():
    p=ROOT/"docs/windows-security-log-scope.md"; text=p.read_text(encoding="utf-8")
    old="""Current controlled progress after the first EventLog-provider batch:\n\n- Windows Security Log UWS review benchmark: `16/422` listed identities encyclopedia-grade (`3.79%`), `406` remaining;\n- benchmark-covered IDs: `1100`, `1101`, `1102`, `1104`, `1105`, `1108`, `4608`, `4624`, `4625`, `4648`, `4672`, `4688`, `4740`, `4768`, `4769`, `4771`;\n- Windows Security Auditing provider coverage remains independently `10/423` encyclopedia-grade with `413` provider-specific identities remaining;\n- Sysmon 15.22: `30/30` complete;\n- global Windows denominator: intentionally unfrozen."""
    new="""Current controlled progress after the second bounded Windows Security Log batch:\n\n- Windows Security Log UWS review benchmark: `26/422` listed identities encyclopedia-grade (`6.16%`), `396` remaining;\n- newly promoted Security-Auditing IDs in this batch: `4609`, `4610`, `4611`, `4612`, `4614`, `4615`, `4616`, `4618`, `4621`, `4622`;\n- Windows Security Auditing provider coverage: `20/423` encyclopedia-grade with `403` provider-specific identities remaining;\n- the provider denominator itself remains frozen at `423` unique IDs / `488` Event ID-version definitions;\n- Sysmon 15.22: `30/30` complete;\n- global Windows denominator: intentionally unfrozen."""
    if old not in text: raise SystemExit("Expected coverage paragraph not found in docs/windows-security-log-scope.md")
    text=text.replace(old,new).replace("After the `1100`-series identities are promoted, rebuild the UWS benchmark queue and continue with the next uncovered listed identity. Because `4608` is already encyclopedia-grade, the next numeric benchmark candidate is `4609`, subject to the same Microsoft/provider/UWS controlled review and provider-specific denominator rules.","After each bounded batch is promoted, rebuild the controlled UWS benchmark queue from fresh `main` and select only identities actually listed by the benchmark and independently supported by Microsoft/provider evidence. The next batch must be derived from that rebuilt queue rather than from a continuous numeric range."); p.write_text(text,encoding="utf-8")

def update_redistribution_inventory():
    p=ROOT/"docs/releases/third-party-redistribution-inventory.json"; doc=json.loads(p.read_text(encoding="utf-8")); row=next(x for x in doc["entries"] if x["id"]=="microsoft-windows-security-documentation"); row["upstream_revision"]="Microsoft Learn Security-Auditing Event documentation/source pages for approved Windows Security exemplars plus controlled provider structural evidence; source prose excluded from Public Preview pack"; evidence=["content/encyclopedia/sources/microsoft-windows-security-event-4608.json",*[f"content/encyclopedia/sources/microsoft-windows-security-event-{eid}.json" for eid in IDS],"content/encyclopedia/sources/microsoft-windows-security-event-4624.json","content/encyclopedia/sources/microsoft-windows-security-event-4625.json","content/encyclopedia/sources/microsoft-windows-security-event-4648.json","content/encyclopedia/sources/microsoft-windows-security-event-4672.json","content/encyclopedia/sources/microsoft-windows-security-event-4740.json","content/encyclopedia/sources/microsoft-windows-security-event-4768.json","content/encyclopedia/sources/microsoft-windows-security-event-4769.json","content/encyclopedia/sources/microsoft-windows-security-event-4771.json","ingestion/inventories/windows-security-auditing-4609-4622-26100.telemetry.json","content/encyclopedia/sources/microsoft-windows-security-auditing-provider-26100-4609-4622.json","ingestion/source-profiles/microsoft-windows-security-auditing-4688-doc.release.json"]; row["review_evidence"]=" + ".join(evidence); dump(p,doc)

def main():
    inv=structural_inventory(); dump(ROOT/"ingestion/inventories/windows-security-auditing-4609-4622-26100.telemetry.json",inv); write_sources(); update_blueprint(); update_coverage(); rebuild_provider_snapshot(); update_existing_tests(); write_batch_tests(); update_docs(); update_redistribution_inventory(); print("batch_ids="+",".join(IDS)); print("inventory_digest="+inv["digest"]); print("coverage=26/422"); print("security_auditing=20/423")
if __name__=="__main__": main()
