#!/usr/bin/env python3
from __future__ import annotations
import json,re,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[1]; BASE='cfb40438e278f23cf74e9a591a98aa2c5a7c4ffd'
m=json.loads((R/'content/encyclopedia/coverage-manifest.json').read_text());s=json.loads((R/'content/encyclopedia/windows-security-auditing-26100.33296-coverage.snapshot.json').read_text());u=m['windows_security_log_review_benchmark'];f=next(x for x in m['families'] if x['id']=='windows-security-auditing');assert (u['completion_ratio'],u['remaining_listed_id_count'],f['encyclopedia_grade_count'],f['remaining_count'])==('106/422',316,100,323);ids=[e['event_id'] for e in s['events'] if e.get('coverage_state')=='ENCYCLOPEDIA_GRADE'];assert len(ids)==100;L=', '.join(f'`{x}`' for x in ids)
def rd(p):return (R/p).read_text()
def wr(p,t):(R/p).write_text(t)
def one(t,p,r,label):
 o,n=re.subn(p,r,t,count=1,flags=re.M);assert n==1,(label,n);return o
p='README.md';t=rd(p);t=one(t,r'^\| Windows Security Auditing \| (.*?) \| \d+ — .*? \| \d+ \|$',lambda x:f'| Windows Security Auditing | {x.group(1)} | 100 — {L} | 323 |','README');wr(p,t)
p='docs/README.md';t=rd(p);t=one(t,r'^- Windows Security Log UWS benchmark: .*$', '- Windows Security Log UWS benchmark: **106/422 encyclopedia-grade listed identities**, `316` remaining','docs UWS');t=one(t,r'^- Windows Security Auditing: .*$', '- Windows Security Auditing: **100/423 encyclopedia-grade**, `323` remaining','docs SA');t=one(t,r'^- Current Windows Security exemplars: .*$',f'- Current Windows Security exemplars: {L}','docs IDs');wr(p,t)
h='- PR #171 Windows Security-Auditing 4720, 4722–4730 encyclopedia promotion — **MERGED / ALL SIX EXACT-HEAD WORKFLOWS SUCCESS** as `ae2a18bb91315efcb5537877480757a0c7f01ebd`; UWS review benchmark advanced to `96/422` and Security-Auditing to `90/423`.'
add=h+'\n- PR #172 authoritative coverage documentation synchronization — **MERGED / ALL APPLICABLE EXACT-HEAD WORKFLOWS SUCCESS** as `1aca4d9b1a215431d6443236bf4a5554b852d34e`.\n- PR #174 Windows Security-Auditing 4731–4742 encyclopedia promotion — **MERGED / ALL SIX EXACT-HEAD WORKFLOWS SUCCESS** as `cfb40438e278f23cf74e9a591a98aa2c5a7c4ffd`; UWS review benchmark advanced to `106/422` and Security-Auditing to `100/423`.'
for p,label in [('docs/current-status.md','status'),('docs/project-state.md','state')]:
 t=rd(p);pat=r'^- Reviewed `main` corpus baseline: .*$' if p.endswith('current-status.md') else r'^- Latest reviewed merged corpus baseline: .*$';rep=f'- Reviewed `main` corpus baseline: `{BASE}` — PR #174 promoted Security-Auditing Event IDs 4731–4742 after all six exact-head workflows completed **SUCCESS**; Windows Security Log UWS benchmark is `106/422`, Windows Security Auditing is `100/423` with `323` remaining, Sysmon remains `30/30`, and the global Windows denominator remains unfrozen.' if p.endswith('current-status.md') else f'- Latest reviewed merged corpus baseline: `{BASE}` — PR #174 promoted Security-Auditing Event IDs 4731–4742 after all six exact-head workflows completed successfully; Windows Security Log UWS benchmark is `106/422`, Windows Security Auditing is `100/423` with `323` remaining, Sysmon remains `30/30`, and the global Windows denominator remains unfrozen.';t=one(t,pat,rep,label+' baseline');
 if p.endswith('project-state.md'):t=one(t,r'^- Last Reviewed Main SHA: `[^`]+`$',f'- Last Reviewed Main SHA: `{BASE}`',label+' sha')
 if '- PR #174 Windows Security-Auditing 4731–4742' not in t:assert h in t;t=t.replace(h,add,1)
 wr(p,t)
p='docs/product-surfaces.md';t=rd(p);t=one(t,r'^\| Windows Security Auditing \| (.*?) \| `\d+/423` — Event IDs .*? \| \d+ \|$',lambda x:f'| Windows Security Auditing | {x.group(1)} | `100/423` — Event IDs {L} | 323 |','surfaces');wr(p,t)
p='docs/roadmap.md';t=rd(p);t=one(t,r'^- Windows Security Log UWS review benchmark: .*$', '- Windows Security Log UWS review benchmark: **106/422** listed identities encyclopedia-grade; **316** remaining;','road UWS');t=one(t,r'^- Windows Security encyclopedia-grade numerator: .*$',f'- Windows Security encyclopedia-grade numerator: **100/423** — Event IDs {L};','road SA');t=one(t,r'^- Windows Security remaining: .*$', '- Windows Security remaining: **323**;','road rem');wr(p,t)
p='docs/windows-sysmon-coverage-plan.md';t=rd(p);t=one(t,r'^The cross-provider Windows Security Log UWS review benchmark is independently .*$', 'The cross-provider Windows Security Log UWS review benchmark is independently `106/422` encyclopedia-grade listed identities with `316` remaining; it is a review benchmark, not a provider denominator.','plan UWS');t=one(t,r'^\| Windows Security Auditing \| 423 unique Event IDs / 488 provider event-version definitions \| \d+ — .*? \| \d+ \|$',f'| Windows Security Auditing | 423 unique Event IDs / 488 provider event-version definitions | 100 — {L} | 323 |','plan row');wr(p,t)
p='ingestion/README.md';t=rd(p);t=one(t,r'^Current reviewed `main` coverage is .*$', 'Current reviewed `main` coverage is **100/423** encyclopedia-grade Event IDs for `Microsoft-Windows-Security-Auditing`, while the cross-provider Security Log UWS review benchmark is **106/422** and Sysmon 15.22 remains **30/30** complete. Moving counters remain authoritative only in the machine-readable coverage ledgers.','ingestion');wr(p,t)
p='ingestion/source-profiles/README.md';t=rd(p);t=one(t,r'^The current reviewed Windows Security Auditing numerator is .*$', 'The current reviewed Windows Security Auditing numerator is **100/423**; the cross-provider Security Log UWS review benchmark is **106/422**; Sysmon 15.22 remains **30/30**. Moving coverage state is authoritative in `content/encyclopedia/coverage-manifest.json`.','profiles');wr(p,t)
allowed={'README.md','docs/README.md','docs/current-status.md','docs/product-surfaces.md','docs/project-state.md','docs/roadmap.md','docs/windows-sysmon-coverage-plan.md','ingestion/README.md','ingestion/source-profiles/README.md'};changed=set(subprocess.check_output(['git','diff','--name-only'],cwd=R,text=True).splitlines());assert changed==allowed,changed;print('coverage=106/422 security_auditing=100/423 docs=9')
