#!/usr/bin/env python3
import hashlib,importlib.util,json,os,subprocess,tempfile
from pathlib import Path
from xml.etree import ElementTree as ET
R=Path(__file__).resolve().parents[1]; IDS=['4731','4732','4733','4734','4735','4737','4738','4739','4741','4742']; RUN=37639160374; ART=11490748773; AD='sha256:0f5a8e3dc94cdf27948ae1ce0a302211acdec40e106b17503e04f672bc16216f'; RAW='sha256-48f4aa4cbca60e5285fcc73b30e877786ee96a3a3ddaab0eba85a3dd3e765c3a'; SID='atlas:source:atlas.source:microsoft-windows-security-auditing-provider-26100-4731-4742'; SV='windows-server-2025-build-26100-security-auditing-4731-4742'
S={'4731':('A security-enabled local group was created','Audit Security Group Management'),'4732':('A member was added to a security-enabled local group','Audit Security Group Management'),'4733':('A member was removed from a security-enabled local group','Audit Security Group Management'),'4734':('A security-enabled local group was deleted','Audit Security Group Management'),'4735':('A security-enabled local group was changed','Audit Security Group Management'),'4737':('A security-enabled global group was changed','Audit Security Group Management'),'4738':('A user account was changed','Audit User Account Management'),'4739':('Domain Policy was changed','Audit Authentication Policy Change'),'4741':('A computer account was created','Audit Computer Account Management'),'4742':('A computer account was changed','Audit Computer Account Management')}
def prev():
 t=subprocess.check_output(['git','show','fc569ff96c057d041469e1b89679f6ce927def26:tools/tmp_apply_security_auditing_4720_4730.py'],text=True);p=Path(tempfile.mkdtemp())/'p.py';p.write_text(t);s=importlib.util.spec_from_file_location('p',p);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
def meta():
 d={}
 for e,(title,sub) in S.items(): d[e]={'title':title,'category':'Policy Change' if e=='4739' else 'Account Management','subcategory':sub,'event_type':'Success','marker':'S','summary':f'Records {title.lower()} while preserving provider-rendered identity and change context.'+(' Version 1 adds MembershipExpirationTime and remains distinct.' if e=='4732' else ''),'requirements':[f'Enable {sub} success auditing.','Preserve exact provider version and subject/target context.'],'interpretation':'Unexpected changes to privileged identities, groups, domain policy or computer principals require validation.','analysis':['Validate against approved identity, access, policy or machine-lifecycle records.'],'correlations':[],'source_version':f'event-{e}-provider-bound-doc','url':f'https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-{e}'}
 return d
def raw():
 p=Path(os.environ['ATLAS_DISCOVERY_JSON']);b=p.read_bytes();assert 'sha256-'+hashlib.sha256(b).hexdigest()==RAW;d=json.loads(b.decode('utf-8-sig'));assert d['unique_event_id_count']==10 and d['event_version_definition_count']==11 and [str(x) for x in d['requested_ids']]==IDS;return d
def shapes(d):
 ns={'e':'http://schemas.microsoft.com/win/2004/08/events'};o={e:[] for e in IDS}
 for v in d['events']:
  x=ET.fromstring(v['template']);f=[(z.attrib['name'],z.attrib.get('inType'),z.attrib.get('outType')) for z in x.findall('e:data',ns)];o[str(v['id'])].append({'version':int(v['version']),'level':v['level'],'fields':f})
 w={'4731':{0:10},'4732':{0:10,1:11},'4733':{0:10},'4734':{0:8},'4735':{0:10},'4737':{0:10},'4738':{0:27},'4739':{0:21},'4741':{0:28},'4742':{0:29}};assert {e:{x['version']:len(x['fields']) for x in a} for e,a in o.items()}==w;b={x['version']:[y[0] for y in x['fields']] for x in o['4732']};assert b[1]==b[0]+['MembershipExpirationTime'];return o
def inv(base,s):
 q=[{'event_id':e,'versions':[{'version':x['version'],'field_count':len(x['fields']),'level':x['level'],'fields':[{'name':n,'in_type':i,'out_type':u} for n,i,u in x['fields']]} for x in s[e]]} for e in IDS];d={'ingestion_contract_version':'1.0.0','inventory_contract_version':'1.0.0','inventory_id':'atlas:inventory:atlas.ingestion:windows-security-auditing-4731-4742-26100','inventory_kind':'telemetry','declared_scope':'Microsoft-Windows-Security-Auditing Event IDs 4731-4735,4737-4739,4741-4742 / Security / Windows Server 2025 build 26100','source_ids':[SID],'inventory_method':'provider-runtime-metadata','inventory_source_version':SV,'expected_identity_count':10,'identity_dimensions':['provider','channel','native-id','product','platform','version'],'scope_metadata':{'provider':'Microsoft-Windows-Security-Auditing','channel':'Security','product':'Windows Server 2025 Datacenter','platform':'Windows','windows_build':'26100','architecture':'64-bit','workflow_run_id':RUN,'artifact_id':ART,'artifact_digest':AD,'raw_artifact_sha256':RAW,'provider_event_version_definition_count':11,'provider_unique_event_id_count':10,'expected_identities':q,'completeness_semantics':'bounded structural evidence for ten identities inside the frozen 423-ID denominator; eleven version definitions preserved'},'guardrails':{'max_unexplained_shrink_percent':0,'max_unexplained_growth_percent':0}};d['digest']=base.digest_without_field(d);return d
def state(base):
 p=R/'content/encyclopedia/coverage-manifest.json';d=json.loads(p.read_text());b=d['windows_security_log_review_benchmark'];assert b['completion_ratio']=='96/422';b.update({'covered_event_ids':sorted(set(b['covered_event_ids'])|set(IDS),key=int),'encyclopedia_grade_listed_id_count':106,'remaining_listed_id_count':316,'completion_ratio':'106/422','completion_percent':25.12});f=next(x for x in d['families'] if x['id']=='windows-security-auditing');assert f['encyclopedia_grade_count']==90;f.update({'encyclopedia_grade_count':100,'remaining_count':323});base.dump(p,d);s=importlib.util.spec_from_file_location('s',R/'tools/content/build_windows_security_coverage_snapshot.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);z=m.build_snapshot();assert (z['encyclopedia_grade_count'],z['remaining_count'],z['completion_ratio'],z['completion_percent'])==(100,323,'100/423',23.64);(R/'content/encyclopedia/windows-security-auditing-26100.33296-coverage.snapshot.json').write_text(json.dumps(z,sort_keys=True,indent=2)+'\n')
def sources(base,M):
 sd=R/'content/encyclopedia/sources';base.dump(sd/'microsoft-windows-security-auditing-provider-26100-4731-4742.json',base.source_record(SID,'microsoft-windows-security-auditing-provider-26100-4731-4742','Microsoft-Windows-Security-Auditing provider metadata — build 26100 — Batch 10',['https://learn.microsoft.com/en-us/windows/win32/wes/windows-event-log'],change={'strategy':'checksum','notes':f'Workflow {RUN}; artifact {ART}; {AD}; {RAW}.'}));ap='https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/plan/Appendix-L--Events-to-Monitor'
 for e in IDS:
  base.dump(sd/f'microsoft-windows-security-event-{e}.json',base.source_record(f'atlas:source:atlas.source:microsoft-windows-security-event-{e}',f'microsoft-windows-security-event-{e}',f'Microsoft Windows Security Event {e}',[M[e]['url'],ap],change={'strategy':'content-diff','notes':'Microsoft semantic authority; provider structural authority.'}));base.dump(sd/f'ultimate-windows-security-event-{e}.json',base.source_record(f'atlas:source:atlas.source:ultimate-windows-security-event-{e}',f'ultimate-windows-security-event-{e}',f'Ultimate Windows Security Event {e}',[f'https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid={e}'],secondary=True,change={'strategy':'manual','notes':'Coverage/Quick Detail only; no bulk ingestion.'}))
def tests(s):
 p=R/'tests/phase51010/test_windows_security_coverage_snapshot.py';t=p.read_text();
 for a,b in [('== 90','== 100'),('== 333','== 323'),('== "90/423"','== "100/423"'),('== 21.28','== 23.64')]: t=t.replace(a,b)
 p.write_text(t);p=R/'tests/phase51010/test_windows_security_auditing_4720_4730.py';t=p.read_text();a='assert (b["encyclopedia_grade_listed_id_count"],b["remaining_listed_id_count"],b["completion_ratio"],b["completion_percent"])==(96,326,"96/422",22.75); assert set(IDS).issubset(set(b["covered_event_ids"])); w=next(x for x in m["families"] if x["id"]=="windows-security-auditing"); assert (w["denominator_count"],w["encyclopedia_grade_count"],w["remaining_count"])==(423,90,333)';b='assert set(IDS).issubset(set(b["covered_event_ids"])) and b["encyclopedia_grade_listed_id_count"]>=96; w=next(x for x in m["families"] if x["id"]=="windows-security-auditing"); assert w["denominator_count"]==423 and w["encyclopedia_grade_count"]>=90';assert a in t;p.write_text(t.replace(a,b));E={e:{str(x['version']):len(x['fields']) for x in s[e]} for e in IDS};(R/'tests/phase51010/test_windows_security_auditing_4731_4742.py').write_text(f'''import json\nfrom pathlib import Path\nR=Path(__file__).resolve().parents[2];E={E!r}\ndef bp():return {{str(x["native_event_id"]):x for x in json.loads((R/"content/encyclopedia/approved-exemplars.json").read_text())["events"] if x.get("namespace")=="microsoft.windows.security"}}\ndef test_versions():\n d=bp();assert all({{str(x["version"]):x["field_count"] for x in d[e]["overview"]["event_versions"]}}==E[e] for e in E);assert {{x["native_name"]:x for x in d["4732"]["fields"]}}["MembershipExpirationTime"]["versions"]==["1"]\ndef test_semantics():\n d=bp();assert d["4739"]["overview"]["subcategory"]=="Audit Authentication Policy Change" and d["4742"]["overview"]["subcategory"]=="Audit Computer Account Management"\ndef test_coverage():\n m=json.loads((R/"content/encyclopedia/coverage-manifest.json").read_text());assert m["windows_security_log_review_benchmark"]["completion_ratio"]=="106/422";f=next(x for x in m["families"] if x["id"]=="windows-security-auditing");assert (f["encyclopedia_grade_count"],f["remaining_count"])==(100,323)\ndef test_binding():\n x=json.loads((R/"ingestion/inventories/windows-security-auditing-4731-4742-26100.telemetry.json").read_text())["scope_metadata"];assert (x["workflow_run_id"],x["artifact_id"],x["provider_event_version_definition_count"])==({RUN},{ART},11) and x["artifact_digest"]=={AD!r} and x["raw_artifact_sha256"]=={RAW!r}\n''')
def docs(base):
 p=R/'docs/windows-security-log-scope.md';t=p.read_text();X=[('after the ninth bounded Windows Security Log batch','after the tenth bounded Windows Security Log batch'),('`96/422` listed identities encyclopedia-grade (`22.75%`), `326` remaining','`106/422` listed identities encyclopedia-grade (`25.12%`), `316` remaining'),('`4720`, `4722`, `4723`, `4724`, `4725`, `4726`, `4727`, `4728`, `4729`, `4730`','`4731`, `4732`, `4733`, `4734`, `4735`, `4737`, `4738`, `4739`, `4741`, `4742`'),('`90/423` encyclopedia-grade with `333` provider-specific identities remaining','`100/423` encyclopedia-grade with `323` provider-specific identities remaining')];
 for a,b in X: assert t.count(a)==1;t=t.replace(a,b)
 p.write_text(t);p=R/'docs/releases/third-party-redistribution-inventory.json';d=json.loads(p.read_text());r=next(x for x in d['entries'] if x['id']=='microsoft-windows-security-documentation');A=[*[f'content/encyclopedia/sources/microsoft-windows-security-event-{e}.json' for e in IDS],'ingestion/inventories/windows-security-auditing-4731-4742-26100.telemetry.json','content/encyclopedia/sources/microsoft-windows-security-auditing-provider-26100-4731-4742.json'];q=[x.strip() for x in r.get('review_evidence','').split(' + ') if x.strip()];r['review_evidence']=' + '.join(q+[x for x in A if x not in q]);base.dump(p,d)
def main():
 m=prev();M=meta();ex=dict(m.EXTRA_FIELD_DETAILS);ex.update({'Dummy':('Additional Information','provider-dummy','Provider-native placeholder; no undocumented semantics assigned.'),'DomainPolicyChanged':('Change Type','domain-policy-changed','Provider-rendered domain policy change indicator.'),'DnsHostName':('Account Attributes','dns-host-name','DNS host name.'),'ServicePrincipalNames':('Account Attributes','service-principal-names','Provider-rendered SPNs.'),'ComputerAccountChange':('Change Type','computer-account-change','Provider-rendered computer-account change indicator.')});
 for n,v in {'ROOT':R,'NOW':'2026-10-07T14:45:00Z','IDS':IDS,'RUN_ID':RUN,'ARTIFACT_ID':ART,'ARTIFACT_DIGEST':AD,'RAW_SHA256':RAW,'STRUCTURAL_ID':SID,'STRUCTURAL_VERSION':SV,'META':M,'EXTRA_FIELD_DETAILS':ex}.items():setattr(m,n,v)
 b8=m.load_previous();b7=b8.load_previous();b6=b7.load_impl();base=b6.load_base();b6.configure_base(base);d=raw();s=shapes(d);i=inv(base,s);base.dump(R/'ingestion/inventories/windows-security-auditing-4731-4742-26100.telemetry.json',i);sources(base,M);base.update_blueprint(s);state(base);tests(s);docs(base);print('coverage=106/422 security_auditing=100/423')
if __name__=='__main__':main()
